name: G-Portal to Firebase Universal Sync

on:
  schedule:
    - cron: '*/16 * * * *' 
  workflow_dispatch: 

jobs:
  sync_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install LFTP
        run: sudo apt-get install -y lftp

      - name: 🛰️ Sync XML Files Only
        run: |
          mkdir -p ./server_data
          lftp -c "set ftp:ssl-allow no; 
          open -u ${{ secrets.GPORTAL_USER }},${{ secrets.GPORTAL_PWD }} -p 50441 ${{ secrets.GPORTAL_HOST }}; 
          mirror --verbose --include-glob *.xml \
          --exclude-glob mods/ \
          --exclude-glob pdlc/ \
          --exclude-glob screenshots/ \
          --exclude-glob shader_cache/ \
          --exclude-glob dedicated_server/temp/ \
          --parallel=5 / ./server_data/" || echo "Sync finished with skips."

      - name: 🚀 Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}'
          projectId: psn-fs22-overlay
          channelId: live
          # This tells the robot to look inside the fs22 folder for the firebase.json
          entryPoint: ./fs22
